### ISSUE TITLE
Use files_custom.conf instead of overwriting default 

### ISSUE THREAD

**Issue by poralix** [tuthost/directadmin-enhanced-ru#1]
Hello,

Thanks for your great work! Here are some possible improvements I'd like to suggest:

Please do not overwrite the default files:

- files_admin.conf
- files_reseller.conf
- files_user.conf

but use **files_custom.conf** instead per this guide: https://help.directadmin.com/item.php?id=35

and whenever it's possible place custom images into:

/usr/local/directadmin/data/skins/enhanced/images/ru/
/usr/local/directadmin/data/skins/enhanced/images/ua/

but not to /usr/local/directadmin/data/skins/enhanced/images

Then the word "неограниченно" is too long it makes right area block too wide.  It is line 447 in /usr/local/directadmin/data/skins/enhanced/lang/ru/internal/command.txt. 

Probably you could use &#8734; (infinity char) from here: http://www.fileformat.info/info/unicode/char/221e/index.htm

Regards,
Alex.

**Comment by tuthost** [comment]
Hello.

Thank for detailed issue descriptions.
We just made changes to skin to use files_custom.conf and to shorten right area block.
